name: Call Reusable Workflow Demo

on:
  workflow_dispatch:

jobs:
  call-reusable:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      environment: staging
    secrets:
      MY_NAME: ${{ vars.MY_NAME }} # Optional secret for testing
