name: Reusable Workflow Demo

on:
  workflow_call:
    inputs:
      environment:
        description: 'Target environment name'
        required: true
        type: string
    secrets:
      API_KEY:
        required: false

jobs:
  print-info:
    runs-on: self-hosted
    steps:
      - name: Print Info
        shell: powershell
        run: |
          Write-Host "=== Running Reusable Workflow ==="
          Write-Host "Environment input: ${{ inputs.environment }}"
          Write-Host "Repository: $env:GITHUB_REPOSITORY"

      - name: Show Secret (runtime check)
        shell: powershell
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          if ($env:API_KEY) {
            Write-Host "API_KEY is provided (masked in logs): $env:API_KEY"
          } else {
            Write-Host "API_KEY is not provided"
          }
