name: Test Docker on Windows Runner

on:
  workflow_dispatch:

jobs:
  run-in-docker:
    runs-on: self-hosted  # Your Windows self-hosted runner
    steps:
      - name: Check runner OS
        run: systeminfo | findstr /B /C:"OS"

      - name: Pull Ubuntu container
        run: docker pull ubuntu:22.04

      - name: Run command inside Ubuntu container
        run: docker run --rm ubuntu:22.04 cat /etc/os-release

      - name: Run multiple commands in container
        run: |
          docker run --rm ubuntu:22.04 bash -c "apt-get update && apt-get install -y curl && curl --version"
