name: Test Artifact Attestation 

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  attestations: write

jobs:
  attest-artifact:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create a test file
        shell: pwsh
        run: |
          "Hello from self-hosted runner" | Out-File -Encoding utf8 hello.txt

      - name: Generate attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: hello.txt

      - name: Upload artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: hello-artifact
          path: hello.txt
