name: Use GitHub CLI Demo (Windows)

on:
  workflow_dispatch:

jobs:
  gh-cli-test:
    runs-on: self-hosted # Windows runner

    steps:
      # 1. Checkout the repo
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Install GitHub CLI if not already installed
      - name: Install GitHub CLI (Windows)
        shell: powershell
        run: |
          if (-Not (Get-Command gh -ErrorAction SilentlyContinue)) {
            choco install gh -y
          }
          gh --version

      # 3. Authenticate with GitHub CLI using GITHUB_TOKEN
      - name: Authenticate GH CLI
        shell: powershell
        run: |
          $env:GITHUB_TOKEN = "${{ github.token }}"
          $env:GITHUB_TOKEN | gh auth login --with-token
          gh auth status

      # 4. List the first 5 issues in this repo
      - name: List Issues
        shell: powershell
        run: gh issue list --limit 5

      # 5. Create a new test issue
      - name: Create Test Issue
        shell: powershell
        run: |
          $title = "Automated Test Issue $(Get-Date -Format 'yyyy-MM-dd_HH-mm-ss')"
          $body = "This issue was created automatically by a GitHub Actions workflow using GitHub CLI on Windows."
          gh issue create --title "$title" --body "$body"
