name: Use GitHub CLI Demo

on:
  workflow_dispatch: # Manual trigger

jobs:
  gh-cli-test:
    runs-on: self-hosted # or ubuntu-latest if using cloud runner
    steps:
      # 1. Checkout repository
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Install GitHub CLI if not available
      - name: Install GitHub CLI (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install gh -y

      - name: Install GitHub CLI (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      # 3. Authenticate GitHub CLI
      - name: Authenticate GH CLI
        shell: bash
        run: |
          echo "${{ github.token }}" | gh auth login --with-token
          gh auth status

      # 4. List first 5 issues in this repo
      - name: List Issues
        shell: bash
        run: gh issue list --limit 5

      # 5. Create a new test issue
      - name: Create Test Issue
        shell: bash
        run: |
          TITLE="Automated Test Issue $(date +%Y-%m-%d_%H-%M-%S)"
          BODY="This issue was created automatically by a GitHub Actions workflow using GitHub CLI."
          gh issue create --title "$TITLE" --body "$BODY"
