name: Use GitHub CLI Demo (Windows)
on:
  workflow_dispatch:

jobs:
  gh-cli-test:
    runs-on: self-hosted

    env:
      GH_TOKEN: ${{ github.token }}  # Required for GitHub CLI in Actions

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install GitHub CLI (Windows)
        shell: powershell
        run: |
          Write-Host "=== Installing GitHub CLI ==="
          choco install gh -y --force
          # Verify gh.exe location
          Get-ChildItem "C:\Program Files\GitHub CLI" -Recurse | Where-Object { $_.Name -eq 'gh.exe' }

      - name: Show Auth Status
        shell: powershell
        run: |
          $GH = "C:\Program Files\GitHub CLI\gh.exe"
          & $GH auth status

      - name: List Issues
        shell: powershell
        run: |
          $GH = "C:\Program Files\GitHub CLI\gh.exe"
          & $GH issue list --limit 5

      - name: Create Test Issue
        shell: powershell
        run: |
          $GH = "C:\Program Files\GitHub CLI\gh.exe"
          $title = "Automated Test Issue $(Get-Date -Format 'yyyy-MM-dd_HH-mm-ss')"
          $body = "Created automatically using GitHub CLI on Windows self-hosted runner with GH_TOKEN env."
          & $GH issue create --title "$title" --body "$body"
