name: Use GitHub CLI
on:
  workflow_dispatch:

jobs:
  gh-cli-test:
    runs-on: self-hosted # Windows runner

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install GitHub CLI (Windows)
        shell: powershell
        run: |
          Write-Host "=== Installing GitHub CLI ==="
          choco install gh -y --force
          # Verify location
          Get-ChildItem "C:\Program Files\GitHub CLI" -Recurse | Where-Object { $_.Name -eq 'gh.exe' }

      - name: Authenticate GH CLI
        shell: powershell
        run: |
          $GH = "C:\Program Files\GitHub CLI\gh.exe"
          $env:GITHUB_TOKEN = "${{ github.token }}"
          $env:GITHUB_TOKEN | & $GH auth login --with-token
          & $GH auth status

      - name: List Issues
        shell: powershell
        run: |
          $GH = "C:\Program Files\GitHub CLI\gh.exe"
          & $GH issue list --limit 5

      - name: Create Test Issue
        shell: powershell
        run: |
          $GH = "C:\Program Files\GitHub CLI\gh.exe"
          $title = "Automated Test Issue $(Get-Date -Format 'yyyy-MM-dd_HH-mm-ss')"
          $body = "Created automatically using GitHub CLI on Windows self-hosted runner."
          & $GH issue create --title "$title" --body "$body"
