name: Use Secrets Demo (Windows)

on:
  workflow_dispatch:

jobs:
  use-secrets:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 1. Access secret using env
      - name: Access secret in PowerShell
        shell: powershell
        env:
          MY_TEST_SECRET: ${{ secrets.MY_TEST_SECRET }}
        run: |
          Write-Host "=== Testing GitHub Actions Secrets ==="
          # Masked in logs automatically
          Write-Host "Secret Value (masked in logs): $env:MY_TEST_SECRET"

      # 2. Use secret in a conditional step
      - name: Conditional based on secret
        shell: powershell
        env:
          MY_TEST_SECRET: ${{ secrets.MY_TEST_SECRET }}
        run: |
          if ($env:MY_TEST_SECRET -eq "super_secret_value") {
            Write-Host "✅ Secret matched expected value"
          } else {
            Write-Host "⚠️ Secret did not match"
          }
